<?php

/**
 * @file confwizard.module
 * Feature Config Wizard
 */

/**
 * Implementation of hook_perm
 */
function confwizard_perm() {
  return array('administer confwizard', 'follow confwizard');
}


/**
 * Implementation of hook_help
 */
function confwizard_help($path, $arg) {
  switch($path) {
    case "admin/settings/features":
      return t("Here you can configure any features which have been installed recently, if they need configuring. Click on the links to go to the relevant configuration pages.");
    break;
    case "admin/settings":
      $status = confwizard_requirements("runtime");
      $sev = $status['confwizard']['severity'];
      if (isset($sev) && $sev > REQUIREMENT_OK) {
        drupal_set_message($status['confwizard']['value'], ($sev > REQUIREMENT_WARNING ? "error" : "warning"));
      }
    break;
  }

}

/**
 * Implementation of hook_menu
 */
function confwizard_menu() {
  $items['admin/settings/features'] = array(
    'title' => 'Features',
    'description' => 'Configure any installed features on your site',

    'page callback' => 'drupal_get_form',
    'page arguments' => array('confwizard_form_follow'),

    'access arguments' => array('follow confwizard'),

    'file' => 'confwizard.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/build/features/confwizard'] = array(
    'title' => 'Config Wizard',
    'description' => 'Package up configuration instructions for your features',

    'page callback' => 'drupal_get_form',
    'page arguments' => array('confwizard_form_admin_settings'),

    'access arguments' => array('administer confwizard'),

    'file' => 'confwizard.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 5,
  );

  return $items;
}

/**
 * Menu access callback
 */
function _confwizard_access_admin($perms) {
  foreach($perms as $perm) {
    $access |= user_access($perm);
  }
  return $access;
}

/**
 * Implementation of hook_requirements
 */
function confwizard_requirements($phase) {
  if ($phase != "runtime") { return; }

  $requirements['confwizard'] = array(
    'title' => t("Features Config Wizard"),
    'value' => t('All features are currently fully configured'),
    'severity' => REQUIREMENT_OK
  );

  module_load_include("inc", "confwizard", "confwizard.admin");
  $follows = confwizard_db_get_urls();
  foreach($follows as $follow) {
    if (!$follow['done']) {
      $requirements['confwizard']['value'] = t('Some features installed on your site are not currently configured. ')
        . l('Please click here to configure these features.', 'admin/settings/features');
      $requirements['confwizard']['severity'] = REQUIREMENT_WARNING;
    }
  }
  return $requirements;
}
